services:
  signaling-server:
    container_name: signaling-server
    build: ./signaling-server
    ports:
      - "8080:8080"
    networks:
      - webrtc-network

  client:
    container_name: client
    build: ./client
    ports:
      - "8000:80"
    networks:
      - webrtc-network

  sender:
    container_name: sender
    build: ./sender
    environment:
      - HOST_IP  # ← entry.sh 内で動的に設定される
    # ports:
    #   - "50000-51000:50000-51000/udp"
    depends_on:
      - signaling-server
    networks:
      - webrtc-network

  turn-server:
    container_name: turn-server
    build: ./turnserver
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
    networks:
      - webrtc-network

networks:
  webrtc-network:
    driver: bridge
