services:
  signaling-server:
    container_name: signaling-server
    build: ./signaling-server
    ports:
      - "8080:8080"
    networks:
      - webrtc-network

  client:
    container_name: client
    build: ./client
    ports:
      - "8000:80"
    networks:
      - webrtc-network

  sender:
    container_name: sender
    build: ./sender
    depends_on:
      - signaling-server
    networks:
      - webrtc-network

  stun-server:
    image: coturn/coturn
    container_name: stun-server
    command: ["turnserver", "-n", "--no-auth", "--listening-port=3478"]
    ports:
      - "3478:3478/udp"     # STUN port exposed to localhost
    networks:
      - webrtc-network

networks:
  webrtc-network:
    driver: bridge
