services:
  signaling-server:
    container_name: signaling-server
    build: ./signaling-server
    ports:
      - "8080:8080"
    networks:
      - webrtc-network

  client:
    container_name: client
    build: ./client
    ports:
      - "8000:80"
    networks:
      - webrtc-network

  sender:
    container_name: sender
    build: ./sender
    # ports:
    #   - "50000-51000:50000-51000/udp"
    depends_on:
      - signaling-server
    networks:
      - webrtc-network


networks:
  webrtc-network:
    driver: bridge
